import os
import shutil
import subprocess

print("remove webcorn build and dist directory...")
shutil.rmtree('../../build', ignore_errors=True)
shutil.rmtree('../../dist', ignore_errors=True)
subprocess.run([shutil.which('npm'), 'install'], cwd="../..")
subprocess.run([shutil.which('npm'), 'run', 'build'], cwd="../..")
print("remove docs directory...")
shutil.rmtree('../../docs', ignore_errors=True)
subprocess.run([shutil.which('npm'), 'install'])
subprocess.run([shutil.which('npm'), 'run', 'build'])
print("copy index.html...")
shutil.copy('public/index.html', '../../docs')
print("copy loading.html...")
shutil.copy('public/loading.html', '../../docs')
print("copy django.html...")
shutil.copy('public/django.html', '../../docs/project_django')
print("copy fastapi.html...")
shutil.copy('public/fastapi.html', '../../docs/project_fastapi')
print("copy flask.html...")
shutil.copy('public/flask.html', '../../docs/project_flask')
print("copy wagtail.html...")
shutil.copy('public/wagtail.html', '../../docs/project_wagtail')
print("generate project_django.zip...")
shutil.make_archive('../../docs/project_django/project_django', 'zip', 'public', 'project_django')
print("generate project_fastapi.zip...")
shutil.make_archive('../../docs/project_fastapi/project_fastapi', 'zip', 'public', 'project_fastapi')
print("generate project_flask.zip...")
shutil.make_archive('../../docs/project_flask/project_flask', 'zip', 'public', 'project_flask')
print("generate project_wagtail.zip...")
shutil.make_archive('../../docs/project_wagtail/project_wagtail', 'zip', 'public', 'project_wagtail')
print('run http server...')
os.chdir('../../docs')
from http.server import test, SimpleHTTPRequestHandler
test(SimpleHTTPRequestHandler)