import shutil
import subprocess

subprocess.run([shutil.which('npm'), 'run', 'build'])
print("remove dist directory...")
shutil.rmtree('dist', ignore_errors=True)
print("copy server files...")
shutil.copytree('../../dist/server', 'dist/project_django/server')
shutil.copytree('../../dist/server', 'dist/project_flask/server')
shutil.copytree('../../dist/server', 'dist/project_fastapi/server')
print("copy service-worker.mjs...")
shutil.copy('../../dist/service-worker.mjs', 'dist')
print("copy style.css...")
shutil.copy('../../dist/style.css', 'dist')
print("copy project_django.zip...")
shutil.copy('../../dist/project_django.zip', 'dist')
print("copy project_flask.zip...")
shutil.copy('../../dist/project_flask.zip', 'dist')
print("copy project_fastapi.zip...")
shutil.copy('../../dist/project_fastapi.zip', 'dist')
print('run fry server...')
subprocess.run([shutil.which('fry'), 'run'])